select*from CUSTOMERS

select*from ORDERS2

SELECT ID, NAME, AMOUNT, DATE FROM CUSTOMERS LEFT JOIN ORDERS2 ON CUSTOMERS.ID = ORDERS2.CUSTOMER_ID
UNION ALL
SELECT  ID, NAME, AMOUNT, DATE
FROM CUSTOMERS
RIGHT JOIN ORDERS2
ON CUSTOMERS.ID = ORDERS2.CUSTOMER_ID; 
SELECT  ID, NAME, AMOUNT, DATE 
     FROM CUSTOMERS 
     LEFT JOIN ORDERS2 
     ON CUSTOMERS.ID = ORDERS2.CUSTOMER_ID
EXCEPT 
     SELECT  ID, NAME, AMOUNT, DATE 
     FROM CUSTOMERS 
     RIGHT JOIN ORDERS2 
     ON CUSTOMERS.ID = ORDERS2.CUSTOMER_ID; 
     
SELECT*FROM CUSTOMERS;

CREATE INDEX customers_idx ON CUSTOMERS (ID, NAME, AGE, ADDRESS, SALARY);

DROP INDEX customers_idx ON CUSTOMERS;

sp_helpindex CUSTOMERS;